#!/bin/bash

# This script can be run with anything in the first argument position to reload bspwm in place
# (Because I'm great at scripting)

# Daemons 
if [ -z $1 ]
  then
    conky -d
    compton -b
    redshift -c /home/intrepidpig/.config/redshift/redshift.conf & # Set your latidude and longitude here
    sxhkd &
    polybar main &
    dunst &
	./batnotify &
fi

bspc monitor -d web terminal code game chat misc music video trash long

# Set path to desired desktop background image
feh --bg-scale /home/intrepidpig/dl/zelda.jpg

bspc config window_gap			    16
bspc config border_width		    1

bspc config click_to_focus			true

bspc config borderless_monocle		true
bspc config gapless_monocle		    true

# Colors
bspc config normal_border_color "#30302f"
bspc config active_border_color "#6d6d6d"
bspc config focused_border_color "#a1a1a1"
bspc config presel_feedback_color "#a19f9f"

