#!/bin/bash

echo "None" > /tmp/lastbatnotif
BAT="/sys/class/power_supply/BAT1/capacity"

while [ 1 ]
do
	CHARGE=$(<$BAT)
	if [ ! "$(cat /tmp/lastbatnotif)" = $CHARGE ] ; then
		if [ "$(calc "$CHARGE % 10" | tr -d '\040\011\012\015')" = "0" ] ; then
			if [ $CHARGE -gt 25 ] ; then
				notify-send "Battery: ${CHARGE}%"
			else
				notify-send -u critical "Battery Critical: ${CHARGE}%"
			fi
			echo $CHARGE > /tmp/lastbatnotif
		fi
	fi
	sleep 10
done
