#!/bin/bash

export SXHKD_SHELL='/usr/bin/sh'

RELOAD=FALSE


# Use argument "-r" to reload bspwm in place
for var in "@a"; do
	if [ "$var" == "-r" ]; then
		RELOAD=TRUE
		echo "-r was passed" > bspwm.log
	fi
done

# Daemons 
if [ "$RELOAD" == "FALSE" ]; then
	echo "Started them daemons" >> bspwm.log
    conky -d
    compton -b
#    redshift -c /home/intrepidpig/.config/redshift/redshift.conf & # Set your latidude and longitude here
    sxhkd &
#    polybar main &
    dunst &
#	./batnotify &
fi

echo "Started configuing bspwm" >> bspwm.log

bspc monitor -d I II III IV V VI VII VIII IX X

# Set path to desired desktop background image
feh --bg-scale "/home/intrepidpig/.config/rices/default/wallpaper"

bspc config window_gap			    16
bspc config border_width		    1

bspc config focus_follows_pointer	true

bspc config borderless_monocle		true
bspc config gapless_monocle		    true

# Colors
bspc config normal_border_color "#30302f"
bspc config active_border_color "#6d6d6d"
bspc config focused_border_color "#a1a1a1"
bspc config presel_feedback_color "#a19f9f"

